version: '3.3'

services:
  ghost:
    image: cacregistry.azurecr.io/ghost:latest
    ports: 
    - "80:80"
    restart: always
        
  nginx:
    depends_on:
    - ghost
    image: cacregistry.azurecr.io/nginx-ghost:latest
    ports:
    - "80:80"
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/certbot/conf:/etc/letsencrypt
      - ${WEBAPP_STORAGE_HOME}/certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${WEBAPP_STORAGE_HOME}/certbot/conf:/etc/letsencrypt
      - ${WEBAPP_STORAGE_HOME}/certbot/www:/var/www/certbot
    # override entrypoint to check for auto-renew every 12 hours
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"