version: '3.3'

services:
  ghost:
    image: cacregistry.azurecr.io/ghost:1.0.16
    ports: 
    - "2368:2368"
    restart: always

  nginx:
    depends_on:
    - ghost
    image: cacregistry.azurecr.io/ghost-nginx:latest
    ports:
    - "0:80"
    restart: always

  certbot:
    depends_on:
    - nginx
    image: cacregistry.azurecr.io/certbot:latest
    ports:
    - "80:80"
    restart: always
    volumes:
    - ${WEBAPP_STORAGE_HOME}/certbot/letsencrypt:/etc/letsencrypt