version: '3.3'

services:
  isso:
    image: cacregistry.azurecr.io/isso:dev
    ports: 
    - "8080:8080"
    restart: always
        
  nginx:
    depends_on:
    - isso
    image: cacregistry.azurecr.io/nginx-isso:dev
    ports:
    - "80:80"
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/certbot/conf:/etc/letsencrypt
      - ${WEBAPP_STORAGE_HOME}/certbot/www:/var/www/certbot
  
  certbot:
    image: cacregistry.azurecr.io/certbot:latest
    restart: unless-stopped
    volumes:
      - ${WEBAPP_STORAGE_HOME}/certbot/conf:/etc/letsencrypt
      - ${WEBAPP_STORAGE_HOME}/certbot/www:/var/www/certbot